raw_data:
  items_csv: data/raw/items.csv
  shop_csv: data/raw/shops.csv
  items_categories_csv: data/raw/item_categories.csv
  sales_csv: data/raw/sales_train.csv

processed_data:
  sales_csv: data/processed/sales.csv

clean_data:
  target: item_cnt_day
  percentile: 0.99

group_data:
  group: True
  by: shop_id
  group_number: 0