features:
  features: 
          - item_id
          - date_block_num
          - shop_id
          - item_category_id
          - shop_location
          - shop_city
  target: item_cnt_day
  categorical: 
     - item_id
     - date_block_num
     - shop_id
     - item_category_id
     - shop_location
     - shop_city

train_data: data/processed/sales.csv

dataset:
  start: 3
  window_size: 24

params:
  random_seed: 42
  task_type: GPU
  devices: 0:1
  loss_function: RMSE

gs_params:
  iterations: 
            - 10
            - 50
  learning_rate: 
    - 0.1
    - 0.05
    - 0.01
  depth: 
       - 4
       - 8

shop: 36

model_save: 'models/pfs_'

neptune:
  project: nktrn/predict-future-sales
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5ZjQ4MjNmNy0xOTZkLTQ2NzEtODY1NS0yNDkyZjBjZDBmMDEifQ==
